r1=Tk()
r1.title('QFLY ARTICAL EDITOR')
#r1.geometry('850x750')
r1.iconbitmap('1.ico')
flag1=True
flag2=True
t11=Text(r1,height=20,width=103,undo=True,font=('Times New Roman',13))
t11.grid(row=0,column=0)
menubar=Menu(r1)
filemenu=Menu(menubar, tearoff=0)
filemenu.add_command(label='打开',font=('楷体',13), command=dakai)
filemenu.add_separator()
filemenu.add_command(label='保存',font=('楷体',13),command=baocun)
filemenu.add_command(label='另存为',font=('楷体',13),command=lingcunwei)
filemenu.add_separator()
filemenu.add_command(label='关闭',font=('楷体',13),command=guanbi)
filemenu.add_command(label='退出',font=('楷体',13),command=tuichu)
menubar.add_cascade(label='文件', menu=filemenu)

editmenu=Menu(menubar, tearoff=0)
editmenu.add_command(label='撤销',font=('楷体',13), command=chexiao)
editmenu.add_command(label='恢复',font=('楷体',13), command=huifu)
editmenu.add_separator()
editmenu.add_command(label='颜色',font=('楷体',13),command=yanse)
editmenu.add_command(label='放大',font=('楷体',13),command=fangda)
editmenu.add_command(label='下划线',font=('楷体',13),command=xiahuaxian)
menubar.add_cascade(label='编辑', menu=editmenu)

toolmenu=Menu(menubar, tearoff=0)
toolmenu.add_command(label='转换',font=('楷体',13), command=zhuanhuan)
toolmenu.add_separator()
toolmenu.add_command(label='查找',font=('楷体',13), command=chazhao)
toolmenu.add_command(label='替换',font=('楷体',13),command=tihuan)
menubar.add_cascade(label='工具', menu=toolmenu)

stamenu=Menu(menubar, tearoff=0)
stamenu.add_command(label='单词数',font=('楷体',13), command=shuliang)
stamenu.add_command(label='词频',font=('楷体',13), command=cishu)
stamenu.add_separator()
stamenu.add_command(label='关键词',font=('楷体',13), command=guanjianci)
menubar.add_cascade(label='统计', menu=stamenu)

menubar.add_command(label='163邮箱',command=link)

r1.config(menu=menubar)
mainloop()